'use strict';mix_d("SimilaritiesUICards__p13n-desktop-sims-fbt:p13n-desktop-sims-fbt__iWg3NV3U",["exports","tslib","@c/browser-operations","@c/scoped-dom"],function(t,h,L,M){function u(b){return b&&"object"===typeof b&&"default"in b?b:{"default":b}}var N=u(L),c=u(M),z=function(b){return h.__awaiter(void 0,void 0,void 0,function(){var e,l,a,C,f,d,D,E,v,F,n,G,p,q,w,H,x,t,k,A;return h.__generator(this,function(h){a=c["default"].cardRoot.getElementsByClassName("cardRoot")[0];C=1;a&&a.dataset.count&&(C=
Number(a.dataset.count));a&&a.dataset.components&&(f=JSON.parse(a.dataset.components));a&&a.dataset.addToCart&&(d=JSON.parse(a.dataset.addToCart));a&&a.dataset.priceTotals&&(D=JSON.parse(a.dataset.priceTotals));a&&a.dataset.pointsTotal&&(E=JSON.parse(a.dataset.pointsTotal));if(f&&D){h=f;for(var m=C,u=[],z=[],g=0;g<m;g++){var r=g+1;1<r&&(u[g]=c["default"].cardRoot.getElementsByClassName("thumbnailPlus-"+String(r))[0]);z[g]=c["default"].cardRoot.getElementsByClassName("thumbnail-"+String(r))[0]}var I=
!1,J=0,K="";for(g=0;g<m;g++){r=String(g+1);var y=u[g],B=z[g];h[r]&&h[r].checked?(J++,K+=r,0===g?I=!0:y&&(I?y.style.display="unset":(I=!0,y.style.display="none")),B&&(B.style.display="unset")):(y&&(y.style.display="none"),B&&(B.style.display="none"))}e=J;l=K;v=e;F=D[l];n=c["default"].cardRoot.getElementsByClassName(b.totalLabel)[0];G=c["default"].cardRoot.getElementsByClassName(b.totalAmount)[0];p=c["default"].cardRoot.getElementsByClassName(b.addItems)[0];q=c["default"].cardRoot.getElementsByClassName(b.chooseItems)[0];
w=c["default"].cardRoot.getElementsByClassName(b.actionDetails)[0];0===v?(p&&(p.style.display="none"),n&&(n.style.display="none"),q&&(q.style.display="unset"),w&&(w.style.visibility="hidden")):(F?(n&&G&&(G.innerText=F,n.style.display="block"),p&&(p.style.display="none"),q&&(q.style.display="none")):(p&&(p.style.display="inline-block"),q&&(q.style.display="none"),n&&(n.style.display="none")),w&&(w.style.visibility="visible"));a&&f&&E&&(H=c["default"].cardRoot.getElementsByClassName(b.pointsAmount)[0],
x=c["default"].cardRoot.getElementsByClassName(b.totalPointsLabel)[0],(t=E[l])?x&&H&&(H.innerText=t,x.style.display="block"):x&&(x.style.display="none"));k=c["default"].cardRoot.getElementsByClassName(b.addAllButton)[0];A=void 0;k&&(A=k.getElementsByClassName("a-button-text")[0]);0===v?k&&!k.classList.contains("a-button-disabled")&&k.classList.add("a-button-disabled"):(k&&k.classList.contains("a-button-disabled")&&k.classList.remove("a-button-disabled"),A&&d&&d.length>=v&&(A.innerText=d[v-1]))}return[2]})})},
l;(function(b){b.clickHandler="clickHandler";b.checkHandler="checkHandler";b.popupHandler="popupHandler"})(l||(l={}));var e={simsFbtContainter:"_p13n-desktop-sims-fbt_fbt-desktop_sims-fbt-containter__2Cffh",thumbnailBox:"_p13n-desktop-sims-fbt_fbt-desktop_thumbnail-box__4jnIT",thumbnailPlus:"_p13n-desktop-sims-fbt_fbt-desktop_thumbnail-plus__zdWox",productBox:"_p13n-desktop-sims-fbt_fbt-desktop_product-box__3PBxY",itemDetailsPerAsin:"_p13n-desktop-sims-fbt_fbt-desktop_item-details-per-asin__3DtF1",
fbtItemCheck:"_p13n-desktop-sims-fbt_fbt-desktop_fbt-item-check__pUIoy",addAllButton:"_p13n-desktop-sims-fbt_fbt-desktop_add-all-button__1TRXG",totalLabel:"_p13n-desktop-sims-fbt_fbt-desktop_total-label__dI983",totalPointsLabel:"_p13n-desktop-sims-fbt_fbt-desktop_total-points-label__3r09H",addItems:"_p13n-desktop-sims-fbt_fbt-desktop_add-items__16weX",chooseItems:"_p13n-desktop-sims-fbt_fbt-desktop_choose-items__15UQx",totalAmount:"_p13n-desktop-sims-fbt_fbt-desktop_total-amount__wLVdU",pointsAmount:"_p13n-desktop-sims-fbt_fbt-desktop_points-amount__1SNdT",
priceAddToCartBox:"_p13n-desktop-sims-fbt_fbt-desktop_price-add-to-cart-box__3OUdK",shipMessageBox:"_p13n-desktop-sims-fbt_fbt-desktop_ship-message-box__t-OOr",shippingInfoShowBox:"_p13n-desktop-sims-fbt_fbt-desktop_shipping-info-show-box__17yWM",showDetailsBox:"_p13n-desktop-sims-fbt_fbt-desktop_show-details-box__-R3Xb",showDetails:"_p13n-desktop-sims-fbt_fbt-desktop_show-details__3GnPL",hideDetails:"_p13n-desktop-sims-fbt_fbt-desktop_hide-details__28l17",simsFbtUnselectedItem:"_p13n-desktop-sims-fbt_fbt-desktop_sims-fbt-unselected-item__VQmZx",
simsFbtRows:"_p13n-desktop-sims-fbt_fbt-desktop_sims-fbt-rows__2LJXs",bucketDivider:"_p13n-desktop-sims-fbt_fbt-desktop_bucket-divider__25poP",titleTruncate:"_p13n-desktop-sims-fbt_fbt-desktop_title-truncate__1pPAM",detailRowElement:"_p13n-desktop-sims-fbt_fbt-desktop_detail-row-element__2WDgq",detailRowElementLeftMargin:"_p13n-desktop-sims-fbt_fbt-desktop_detail-row-element-left-margin__UkZ8O",actionDetails:"_p13n-desktop-sims-fbt_fbt-desktop_action-details__18ZiI"};t._operationNames=[];t.card=function(){return h.__awaiter(void 0,
void 0,void 0,function(){var b,m;return h.__generator(this,function(h){b=N["default"].setup().define;if(!c["default"].cardRoot)return[2];z(e);m=!0;b(l.clickHandler,"click",function(a){if(a.event.target){a=c["default"].cardRoot.getElementsByClassName(e.shippingInfoShowBox);var b=c["default"].cardRoot.getElementsByClassName(e.showDetails)[0],f=c["default"].cardRoot.getElementsByClassName(e.hideDetails)[0];b&&(m?(b.style.display="none",f.style.display="unset",a&&([].forEach.call(a,function(a,b){a.style.display=
"block"}),m=!1)):(b.style.display="unset",f.style.display="none",a&&[].forEach.call(a,function(a,b){a.style.display="none"}),m=!0))}});b(l.checkHandler,"click",function(a){a=a.event.target;if(!a||"fbtCheck"===a.id.substr(0,8)){for(;a&&!a.classList.contains(e.fbtItemCheck);)a=a.parentElement;if(a){var b=a.id,f=c["default"].cardRoot.getElementsByClassName("cardRoot")[0],d=void 0;f&&f.dataset.components&&(d=JSON.parse(f.dataset.components));d&&d[b]&&(d[b].checked=!d[b].checked);d&&d[b].checked&&(a.classList.contains(e.simsFbtUnselectedItem)&&
a.classList.remove(e.simsFbtUnselectedItem),a.classList.contains(e.fbtCheckDetails)||a.classList.add(e.fbtCheckDetails));d&&!d[b].checked&&(a.classList.remove(e.fbtCheckDetails),a.classList.add(e.simsFbtUnselectedItem));f.dataset.components=JSON.stringify(d);z(e)}}});return[2]})})}});
